import stylistic from "@stylistic/eslint-plugin";
import jsdoc from "eslint-plugin-jsdoc";
import perfectionist from "eslint-plugin-perfectionist";
import globals from "globals";

import foundry from "./plugin.mjs";

export const recommended = [
  {
    languageOptions: {
      ecmaVersion: "latest",
      globals: { ...globals.browser },
      sourceType: "module"
    },
    plugins: { foundry, jsdoc, perfectionist, "@stylistic": stylistic },
    rules: {
      "@stylistic/array-bracket-spacing": ["warn", "never"],
      "@stylistic/arrow-parens": ["warn", "as-needed", { requireForBlockBody: false }],
      "@stylistic/arrow-spacing": "warn",
      "@stylistic/comma-dangle": ["warn", "never"],
      "@stylistic/comma-spacing": "warn",
      "@stylistic/comma-style": "warn",
      "@stylistic/computed-property-spacing": "warn",
      "@stylistic/dot-location": ["warn", "property"],
      "@stylistic/eol-last": ["error", "always"],
      "@stylistic/function-call-spacing": "warn",
      "@stylistic/indent": ["warn", 2, { SwitchCase: 1 }],
      "@stylistic/key-spacing": "warn",
      "@stylistic/keyword-spacing": "warn",
      "@stylistic/linebreak-style": ["warn", "unix"],
      "@stylistic/lines-between-class-members": "warn",
      "@stylistic/new-parens": ["warn", "always"],
      "@stylistic/no-extra-semi": "warn",
      "@stylistic/no-multi-spaces": ["warn", { ignoreEOLComments: true }],
      "@stylistic/no-multiple-empty-lines": "warn",
      "@stylistic/no-trailing-spaces": "warn",
      "@stylistic/no-whitespace-before-property": "warn",
      "@stylistic/nonblock-statement-body-position": ["warn", "beside"],
      "@stylistic/object-curly-spacing": ["warn", "always"],
      "@stylistic/operator-linebreak": ["warn", "before", {
        overrides: { "-=": "after", "+=": "after", "=": "after" }
      }],
      "@stylistic/quote-props": ["warn", "as-needed", { keywords: false }],
      "@stylistic/quotes": ["warn", "double", { allowTemplateLiterals: "never", avoidEscape: true }],
      "@stylistic/rest-spread-spacing": ["warn", "never"],
      "@stylistic/semi": ["warn", "always"],
      "@stylistic/semi-spacing": "warn",
      "@stylistic/semi-style": ["warn", "last"],
      "@stylistic/space-before-blocks": ["warn", "always"],
      "@stylistic/space-before-function-paren": ["warn", {
        anonymous: "never",
        asyncArrow: "always",
        named: "never"
      }],
      "@stylistic/space-unary-ops": ["warn", { nonwords: false, words: true }],
      "@stylistic/spaced-comment": "warn",
      "@stylistic/switch-colon-spacing": "warn",
      "@stylistic/template-curly-spacing": ["warn", "never"],
      "@stylistic/wrap-iife": ["warn", "inside"],
      "array-callback-return": "warn",
      "constructor-super": "error",
      curly: ["warn", "multi-line"],
      "default-param-last": "warn",
      "dot-notation": "warn",
      eqeqeq: ["warn", "smart"],
      "foundry/jsdoc-no-spaces-around-optional-param-equals": "warn",
      "foundry/no-spaces-around-default-param-equals": "warn",
      "foundry/require-arrow-braces": "warn",
      "foundry/require-method-separator": "warn",
      "foundry/sort-object-keys": "warn",
      "foundry/space-in-control-flow-parens": "warn",
      "func-names": ["warn", "never"],
      "getter-return": ["warn", { allowImplicit: true }],
      "jsdoc/check-access": "warn",
      "jsdoc/check-alignment": "warn",
      "jsdoc/check-param-names": "warn",
      "jsdoc/check-property-names": "warn",
      "jsdoc/check-tag-names": ["warn", { definedTags: ["import"] }],
      "jsdoc/check-types": "warn",
      "jsdoc/check-values": "warn",
      "jsdoc/empty-tags": "warn",
      "jsdoc/implements-on-classes": "warn",
      "jsdoc/multiline-blocks": ["warn", { noSingleLineBlocks: true, singleLineTags: ["inheritDoc", "override"] }],
      "jsdoc/no-bad-blocks": "warn",
      "jsdoc/require-description": ["warn", { checkConstructors: false }],
      "jsdoc/require-hyphen-before-param-description": ["warn", "never", { tags: { property: "never" } }],
      "jsdoc/require-jsdoc": "warn",
      "jsdoc/require-param": "warn",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-param-type": "warn",
      "jsdoc/require-property": "warn",
      "jsdoc/require-property-name": "warn",
      "jsdoc/require-property-type": "warn",
      "jsdoc/require-returns": "warn",
      "jsdoc/require-returns-check": "warn",
      "jsdoc/require-returns-type": "warn",
      "jsdoc/require-yields": "warn",
      "jsdoc/require-yields-check": "warn",
      "jsdoc/type-formatting": ["warn", { objectTypeBracketSpacing: " ", stringQuotes: "double", unionSpacing: "" }],
      "max-len": ["warn", {
        code: 120,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreTrailingComments: true,
        ignoreUrls: true
      }],
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "error",
      "no-constant-condition": "warn",
      "no-constructor-return": "warn",
      "no-delete-var": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-duplicate-imports": ["warn", { includeExports: true }],
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-extra-boolean-cast": ["warn", { enforceForLogicalOperands: true }],
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-implicit-coercion": ["warn", { allow: ["!!"] }],
      "no-implied-eval": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-iterator": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "warn",
      "no-misleading-character-class": "warn",
      "no-mixed-operators": ["warn", {
        groups: [[
          "+", "-", "*", "/", "%", "**",
          "&", "|", "^", "~", "<<", ">>", ">>>",
          "==", "!=", "===", "!==", ">", ">=", "<", "<=",
          "&&", "||", "??",
          "in", "instanceof"
        ]]
      }],
      "no-multi-str": "warn",
      "no-new-func": "warn",
      "no-new-object": "warn",
      "no-new-symbol": "warn",
      "no-new-wrappers": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-proto": "warn",
      "no-regex-spaces": "warn",
      "no-script-url": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-sequences": "warn",
      "no-setter-return": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-unexpected-multiline": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unneeded-ternary": "warn",
      "no-unreachable": "warn",
      "no-unreachable-loop": "warn",
      "no-unsafe-negation": ["warn", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": ["warn", { disallowArithmeticOperators: true }],
      "no-unused-expressions": "warn",
      "no-unused-vars": ["warn", { args: "none" }],
      "no-useless-backreference": "warn",
      "no-useless-call": "warn",
      "no-useless-catch": "warn",
      "no-useless-computed-key": ["warn", { enforceForClassMembers: true }],
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-useless-return": "warn",
      "no-var": "warn",
      "no-void": ["warn", { allowAsStatement: true }],
      "one-var": ["warn", "never"],
      "perfectionist/sort-classes": ["warn", {
        groups: [
          "constructor",
          "static-property",
          "static-method",
          "property",
          "private-property",
          "get-method",
          "method",
          "private-method"
        ],
        type: "alphabetical"
      }],
      "perfectionist/sort-imports": ["warn", {
        groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
        newlinesBetween: 1
      }],
      "perfectionist/sort-modules": ["warn", {
        groups: ["export-class", "class", "export-function", "function"],
        type: "alphabetical"
      }],
      "prefer-numeric-literals": "warn",
      "prefer-object-spread": "warn",
      "prefer-regex-literals": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",
      "symbol-description": "warn",
      "unicode-bom": ["warn", "never"],
      "use-isnan": ["warn", { enforceForIndexOf: true, enforceForSwitchCase: true }],
      "valid-typeof": ["warn", { requireStringLiterals: true }]
    },
    settings: {
      jsdoc: {
        mode: "typescript",
        preferredTypes: { ".<>": "<>", Object: "object", undefined: "void" },
        tagNamePreference: { augments: "extends" }
      }
    }
  }
];
